'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConsoleShow() As Boolean
            Get
                Return CType(Me("ConsoleShow"),Boolean)
            End Get
            Set
                Me("ConsoleShow") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AvatarShow() As Boolean
            Get
                Return CType(Me("AvatarShow"), Boolean)
            End Get
            Set
                Me("AvatarShow") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ViewerEase() As Boolean
            Get
                Return CType(Me("ViewerEase"), Boolean)
            End Get
            Set
                Me("ViewerEase") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Opensim")>
        Public Property GridFolder() As String
            Get
                Return CType(Me("GridFolder"), String)
            End Get
            Set
                Me("GridFolder") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AutoBackup() As Boolean
            Get
                Return CType(Me("AutoBackup"), Boolean)
            End Get
            Set
                Me("AutoBackup") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("8002")>
        Public Property PublicPort() As String
            Get
                Return CType(Me("PublicPort"), String)
            End Get
            Set
                Me("PublicPort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>
        Public Property PublicIP() As String
            Get
                Return CType(Me("PublicIP"), String)
            End Get
            Set
                Me("PublicIP") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property Onlook() As Boolean
            Get
                Return CType(Me("Onlook"), Boolean)
            End Get
            Set
                Me("Onlook") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("DreamWorld")>
        Public Property SimName() As String
            Get
                Return CType(Me("SimName"), String)
            End Get
            Set
                Me("SimName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>
        Public Property CoordX() As String
            Get
                Return CType(Me("CoordX"), String)
            End Get
            Set
                Me("CoordX") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>
        Public Property CoordY() As String
            Get
                Return CType(Me("CoordY"), String)
            End Get
            Set
                Me("CoordY") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("8003")>
        Public Property PrivatePort() As String
            Get
                Return CType(Me("PrivatePort"), String)
            End Get
            Set
                Me("PrivatePort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("256")>
        Public Property SizeX() As String
            Get
                Return CType(Me("SizeX"), String)
            End Get
            Set
                Me("SizeX") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("256")>
        Public Property SizeY() As String
            Get
                Return CType(Me("SizeY"), String)
            End Get
            Set
                Me("SizeY") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("8001")>
        Public Property LoopBack() As String
            Get
                Return CType(Me("LoopBack"), String)
            End Get
            Set
                Me("LoopBack") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("3307")>
        Public Property MySqlPort() As String
            Get
                Return CType(Me("MySqlPort"), String)
            End Get
            Set
                Me("MySqlPort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1440")>
        Public Property AutobackupInterval() As String
            Get
                Return CType(Me("AutobackupInterval"), String)
            End Get
            Set
                Me("AutobackupInterval") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("7")>
        Public Property KeepForDays() As Integer
            Get
                Return CType(Me("KeepForDays"), Integer)
            End Get
            Set
                Me("KeepForDays") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("secret")>
        Public Property Password() As String
            Get
                Return CType(Me("Password"), String)
            End Get
            Set
                Me("Password") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Wifi")>
        Public Property AdminFirst() As String
            Get
                Return CType(Me("AdminFirst"), String)
            End Get
            Set
                Me("AdminFirst") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Admin")>
        Public Property AdminLast() As String
            Get
                Return CType(Me("AdminLast"), String)
            End Get
            Set
                Me("AdminLast") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("email@somewhere.com")>
        Public Property AdminEmail() As String
            Get
                Return CType(Me("AdminEmail"), String)
            End Get
            Set
                Me("AdminEmail") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Console")>
        Public Property ConsoleUser() As String
            Get
                Return CType(Me("ConsoleUser"), String)
            End Get
            Set
                Me("ConsoleUser") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("secret")>
        Public Property ConsolePass() As String
            Get
                Return CType(Me("ConsolePass"), String)
            End Get
            Set
                Me("ConsolePass") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("8004")>
        Public Property RegionPort() As String
            Get
                Return CType(Me("RegionPort"), String)
            End Get
            Set
                Me("RegionPort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("1500")>
        Public Property ChatTime() As Integer
            Get
                Return CType(Me("ChatTime"), Integer)
            End Get
            Set
                Me("ChatTime") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property ViewerInstalled() As Boolean
            Get
                Return CType(Me("ViewerInstalled"), Boolean)
            End Get
            Set
                Me("ViewerInstalled") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("0")>
        Public Property ImageNum() As Integer
            Get
                Return CType(Me("ImageNum"), Integer)
            End Get
            Set
                Me("ImageNum") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property allow_grid_gods() As Boolean
            Get
                Return CType(Me("allow_grid_gods"), Boolean)
            End Get
            Set
                Me("allow_grid_gods") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property region_owner_is_god() As Boolean
            Get
                Return CType(Me("region_owner_is_god"), Boolean)
            End Get
            Set
                Me("region_owner_is_god") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property region_manager_is_god() As Boolean
            Get
                Return CType(Me("region_manager_is_god"), Boolean)
            End Get
            Set
                Me("region_manager_is_god") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property parcel_owner_is_god() As Boolean
            Get
                Return CType(Me("parcel_owner_is_god"), Boolean)
            End Get
            Set
                Me("parcel_owner_is_god") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("60")>
        Public Property TimerInterval() As Integer
            Get
                Return CType(Me("TimerInterval"), Integer)
            End Get
            Set
                Me("TimerInterval") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property AccountConfirmationRequired() As Boolean
            Get
                Return CType(Me("AccountConfirmationRequired"), Boolean)
            End Get
            Set
                Me("AccountConfirmationRequired") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Gmail for notification")>
        Public Property SmtpUsername() As String
            Get
                Return CType(Me("SmtpUsername"), String)
            End Get
            Set
                Me("SmtpUsername") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("Gmail password")>
        Public Property SmtpPassword() As String
            Get
                Return CType(Me("SmtpPassword"), String)
            End Get
            Set
                Me("SmtpPassword") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property RunOnce() As Boolean
            Get
                Return CType(Me("RunOnce"), Boolean)
            End Get
            Set
                Me("RunOnce") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property SkipUpdateCheck() As Boolean
            Get
                Return CType(Me("SkipUpdateCheck"), Boolean)
            End Get
            Set
                Me("SkipUpdateCheck") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property DiagFailed() As Boolean
            Get
                Return CType(Me("DiagFailed"), Boolean)
            End Get
            Set
                Me("DiagFailed") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property DnsName() As String
            Get
                Return CType(Me("DnsName"), String)
            End Get
            Set
                Me("DnsName") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("True")>
        Public Property WebStats() As Boolean
            Get
                Return CType(Me("WebStats"), Boolean)
            End Get
            Set
                Me("WebStats") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("8002")>
        Public Property HttpPort() As String
            Get
                Return CType(Me("HttpPort"), String)
            End Get
            Set
                Me("HttpPort") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("")>
        Public Property MachineID() As String
            Get
                Return CType(Me("MachineID"), String)
            End Get
            Set
                Me("MachineID") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property LoopBackDiag() As Boolean
            Get
                Return CType(Me("LoopBackDiag"), Boolean)
            End Get
            Set
                Me("LoopBackDiag") = Value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.DefaultSettingValueAttribute("False")>
        Public Property UPnPDiag() As Boolean
            Get
                Return CType(Me("UPnPDiag"), Boolean)
            End Get
            Set
                Me("UPnPDiag") = Value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Outworldz.My.MySettings
            Get
                Return Global.Outworldz.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
